[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rouse"
version = "0.0.0"
authors = [
  { name="Simon Grosse-Holz", email="sgh256@mit.edu" }
]
description = "An implementation of the Rouse model of polymer dynamics"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/OpenTrajectoryAnalysis/rouse"
"Bug Tracker" = "https://github.com/OpenTrajectoryAnalysis/rouse/issues"
